# Generated by Django 5.1.2 on 2024-10-16 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_solicitudretiro_descripcion_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SolicitudRetiro',
        ),
    ]
