# Generated by Django 5.1.2 on 2024-10-16 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_delete_solicitudretiro'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudRetiro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ruta_optima', models.CharField(max_length=300, null=True)),
            ],
        ),
    ]
