# Generated by Django 5.1.2 on 2024-10-16 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SolicitudRetiro',
        ),
    ]
