# Generated by Django 5.1.2 on 2024-10-16 21:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0019_delete_solicitudretiro'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoResiduo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_residuo', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudRetiro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cant_residuos', models.IntegerField()),
                ('direccion', models.CharField(max_length=100)),
                ('descripcion', models.TextField(max_length=400, null=True)),
                ('destino_final', models.CharField(max_length=100, null=True)),
                ('ruta_optima', models.CharField(max_length=300, null=True)),
                ('valor', models.IntegerField(null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tipo_residuo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tiporesiduo')),
            ],
        ),
    ]
